# Generated by Django 5.2.5 on 2025-09-02 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='ФИО гостя')),
                ('is_approved', models.BooleanField(blank=True, null=True, verbose_name='Заявка одобрена сотрудником')),
                ('is_validated', models.BooleanField(blank=True, null=True, verbose_name='Пропуск выдан охраной')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
