# Generated by Django 5.2.5 on 2025-09-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО сотрудника')),
                ('chat_id', models.IntegerField(verbose_name='ID чата в тг')),
            ],
        ),
        migrations.AlterField(
            model_name='pass',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker', verbose_name='Сотрудник'),
        ),
    ]
